# Site settings
title: Abe Ltd
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Abe Ltd
user_description: I'm Alex a Software Developer from Guernsey. I have over 15 years of experience developing solutions for enterprise systems as well as providing support for infrastructure and networking. Developing in the Microsoft stack allows robust and stable solutions for all client requirements. 
user_title: Software Engineer
email: alex@abe-ltd.gg
# twitter_username: lorem_ipsum
# instagram_username: mauriciourraco7
# facebook_username: mauricio.urraco
# linkedin_username: murraco
github_username:  abe-ltd
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
